/* Offline PDF preparation UI contracts. Stubbed network; no model calls. */
'use strict';
const fs=require('node:fs'),path=require('node:path'),vm=require('node:vm'),assert=require('node:assert/strict');
const html=fs.readFileSync(path.join(__dirname,'../prototypes/review-workbench/canonical.html'),'utf8');
const script=html.match(/<script>([\s\S]*?)<\/script>/)[1].replace(/\nboot\(\);\n/,'\n');
const nodes=new Map(),events={},requests=[];let responder=async()=>({}),status=200;
function node(id){if(!nodes.has(id))nodes.set(id,{id,value:'',textContent:'',innerHTML:'',hidden:false,disabled:false,checked:false,tagName:'DIV',dataset:{},classList:{toggle(){}},addEventListener(){},setAttribute(){},contains(x){return x?.insidePreparation===true;},focus(){},scrollIntoView(){}});return nodes.get(id);}
const document={getElementById:node,activeElement:null,addEventListener(type,fn){(events[type]??=[]).push(fn);}};
const context=vm.createContext({document,URL,URLSearchParams,location:{origin:'http://localhost',pathname:'/',search:''},history:{replaceState(){}},navigator:{clipboard:{writeText:async()=>{}}},setTimeout(){return 1;},clearTimeout(){},console,fetch:async(url,options={})=>{requests.push({url,options});const data=await responder(url,options);return {ok:status<400,status,json:async()=>data};}});
vm.runInContext(script,context);const run=code=>vm.runInContext(code,context);let count=0;
function check(value,message){assert.ok(value,message);count++;}
function field(row,key,value,extra={}){context.edit={dataset:{preparationRow:String(row),preparationField:key,...extra},value,checked:value===true};return run('updatePreparationField(edit)');}
const fixture={id:'prep-1',filename:'source <img src=x onerror=alert(1)>.pdf',status:'ready',revision:2,pages:[{page:1,text:'The battery shall stay below 28 V.\nV means volts.\n<script>document text</script>'},{page:2,text:'Additional source context.'}],warnings:['Inspect tables <script>warning</script>'],errors:[],items:[{id:'R1',kind:'requirement',text:'The battery shall stay below 28 V.',citations:[{page:1,quote:'The battery shall stay below 28 V.'}],context_ids:['D1'],rationale:'<img src=x onerror=alert(1)>',selected:true,note:'',source_verified:true,issues:[]},{id:'D1',kind:'definition',text:'V means volts.',citations:[{page:1,quote:'V means volts.'}],context_ids:[],rationale:'Shared unit definition',selected:true,note:'',source_verified:true,issues:[]},{id:'E1',kind:'exception',text:'<script>row text</script>',citations:[{page:1,quote:'</textarea><img src=x onerror=alert(1)>'}],context_ids:[],rationale:'',selected:false,note:'<script>reviewer note</script>',issues:['<script>issue</script>']}]};
const reviewed=JSON.parse(JSON.stringify(fixture));reviewed.status='reviewed';reviewed.revision=3;reviewed.items[0].selected=true;reviewed.items[1].selected=true;reviewed.items[2].selected=false;reviewed.review={reviewer:'Engineer',note:'Reviewed context and quotations'};
(async()=>{
check(html.indexOf('id="preparation-panel"')<html.indexOf('id="run-form"'),'Optional preparation appears before the unchanged conversion form');
check(html.includes('id="source-file"')&&html.includes('Assessment assertions are optional'),'Prepared JSON upload remains available and assertions are separate');
check(html.includes('id="preparation-effort"')&&html.includes('apply to the next proposal only'),'Proposal effort can be selected independently for the next call');
run("preparation.config={default_model:'default-proposer',reasoning_effort:'low',reasoning_efforts:['low','medium','high','xhigh','max','ultra']};configurePreparationEffort()");
check(node('preparation-effort').innerHTML.includes('Server default (low)')&&node('preparation-effort').value==='','Default choice reports the actual server effort without overriding it');
check(['low','medium','high','xhigh','max','ultra'].every(value=>node('preparation-effort').innerHTML.includes(`value="${value}"`)),'Effort choices come from supported server configuration');
node('preparation-effort').value='medium';run('configurePreparationEffort()');check(node('preparation-effort').value==='medium','Refreshing configuration preserves an explicit supported effort selection');
run("preparation.config={};configurePreparationEffort()");check(node('preparation-effort').innerHTML.includes('value="high"')&&!node('preparation-effort').innerHTML.includes('undefined'),'Legacy service configuration retains portable effort choices');
node('preparation-effort').value='';

run(`acceptPreparation(${JSON.stringify(fixture)});renderPreparation();`);
check(run('preparationDraft().items.every(row=>!row.selected)'),'LLM proposals cannot preselect approved requirements or context');
check(run('preparationDraft().items[0].context_ids[0]')==='D1','Suggested definition links survive draft initialization');
const first=node('preparation-body').innerHTML;
check(!first.includes('<script>')&&!first.includes('<img src=x'),'PDF content, rationale, issues, notes and citations are HTML escaped');
check(first.includes('&lt;/textarea&gt;')&&first.includes('rel="noopener noreferrer"'),'Hostile quotation cannot break its editor; original PDF opens safely');
check(node('preparation-page-text').textContent.includes('<script>document text</script>')&&!node('preparation-page-text').innerHTML,'Source preview uses textContent, preserving literal PDF markup');
check(first.includes('shared across the selected requirements')&&first.includes('do not create formal solver assumptions'),'Context scope and formal assumption boundary are explicit');
check(first.includes('This does not verify the proposed meaning'),'Matching quotation is not presented as semantic verification');
for(const kind of ['definition','scope','constraint','assumption','dependency','exception','informative','unresolved'])check(first.includes(`value="${kind}"`),`Role ${kind} can be retained or reclassified`);
field(0,'text','Edited source wording');field(0,'note','Human explanation');
run(`acceptPreparation(${JSON.stringify({...fixture,status:'ready'})});renderPreparation();`);
check(run('preparationDraft().items[0].text')==='Edited source wording','Polling preserves dirty wording and notes');
check(run('preparationDraft().dirty')&&node('preparation-use').disabled,'Unsaved edits prevent packet handoff');
run(`acceptPreparation(${JSON.stringify({...fixture,revision:9})});renderPreparation();`);
check(run('preparationDraft().revision')===2&&run('preparationDraft().conflict'),'Server revision changes do not silently rebase edits');
check(node('preparation-body').innerHTML.includes('Your edits are preserved')&&node('preparation-body').innerHTML.includes('Latest saved rows'),'Conflict exposes both preserved draft and saved comparison');
run("preparationAction('rebase',{dataset:{}})");
check(run('preparationDraft().revision')===9&&!run('preparationDraft().acknowledge'),'Explicit rebase requires renewed acknowledgment');
run(`acceptPreparation(${JSON.stringify({...fixture,id:'prep-other'})});acceptPreparation(${JSON.stringify({...fixture,revision:9})});`);
check(run('preparationDraft().items[0].note')==='Human explanation','Navigating between preparations retains unsaved drafts');
document.activeElement={insidePreparation:true,tagName:'TEXTAREA'};node('preparation-body').innerHTML='Editing source';responder=async()=>({...fixture,revision:9});await run('pollPreparation()');
check(node('preparation-body').innerHTML==='Editing source','Polling does not replace a focused review editor');document.activeElement=null;
document.activeElement={insidePreparation:true,tagName:'SELECT',id:'preparation-page'};node('preparation-body').innerHTML='Waiting for proposal';await run('pollPreparation()');
check(node('preparation-body').innerHTML!=='Waiting for proposal','Completed polling updates the review when only the source page selector is focused');document.activeElement=null;
run("preparationAction('add-item',{dataset:{}})");
check(run('preparationDraft().items.at(-1).selected')===false&&run('preparationDraft().items.at(-1).citations[0].page')===1,'Manual additions start unchecked with editable page citations');
run('preparation.drafts.clear();preparation.current=null;');
const file={name:'spec #1 & test.pdf',size:512,binary:'%PDF-1.7\0binary'};context.pdfFile=file;
responder=async()=>({...fixture,status:'extracted',revision:1,items:[]});const uploadStart=requests.length;await run('uploadPreparation(pdfFile)');
const upload=requests[uploadStart];check(upload.options.body===file&&upload.options.headers['Content-Type']==='application/pdf','Upload sends the PDF binary body rather than JSON');
check(upload.url.endsWith('filename=spec%20%231%20%26%20test.pdf'),'Filename is URL encoded');
check(requests.length===uploadStart+1&&run('preparation.current.status')==='extracted','Upload extracts locally without implicitly proposing or converting');
context.badFile={name:'not.pdf',size:21*1024*1024};await run('uploadPreparation(badFile)');check(requests.length===uploadStart+1&&node('preparation-error').textContent.includes('size limit'),'Oversize PDF is rejected before upload');
node('input-model').value='selected-generator';node('preparation-model').value='';responder=async()=>({...fixture,status:'queued',revision:2,items:[]});await run('proposePreparation()');
check(JSON.parse(requests.at(-1).options.body).model==='selected-generator','Proposal uses the current generation model unless explicitly overridden');
check(requests.at(-1).url.endsWith('/propose')&&run('preparationWorking()'),'Explicit proposal queues one model request');
check(!('reasoning_effort' in JSON.parse(requests.at(-1).options.body)),'Server-default effort is omitted from the proposal request');
responder=async()=>fixture;await run('pollPreparation()');
check(run('preparationDraft().items.length')===3&&run('preparationDraft().items.every(row=>!row.selected)'),'Completed proposal polling populates unchecked rows');
node('preparation-model').value='custom-proposer';node('preparation-effort').value='high';responder=async()=>({...fixture,status:'queued',items:[],configuration:{model:'custom-proposer',reasoning_effort:'high'},attempts:[{number:1,model:'custom-proposer',reasoning_effort:'high',status:'queued'}]});await run('proposePreparation()');
const overriddenProposal=JSON.parse(requests.at(-1).options.body);check(overriddenProposal.model==='custom-proposer'&&overriddenProposal.reasoning_effort==='high','Explicit model and effort are sent together for this proposal');
check(node('preparation-status').innerHTML.includes('Model: custom-proposer · Reasoning effort: high'),'Current status shows effective recorded attempt configuration');
node('preparation-model').value='next-model';node('preparation-effort').value='low';run('updatePreparationStatus()');
check(node('preparation-status').innerHTML.includes('Model: custom-proposer · Reasoning effort: high')&&!node('preparation-status').innerHTML.includes('next-model'),'Changing future proposal controls cannot relabel an existing attempt');
check(run('preparation.current.configuration.reasoning_effort')==='high'&&!run('preparationDraft().dirty'),'Configuration edits do not mutate saved settings or the source review');
node('preparation-model').value='';node('preparation-effort').value='';responder=async()=>fixture;await run('pollPreparation()');

field(0,'selected',true);run('preparationDraft().reviewer="Engineer";preparationDraft().acknowledge=true');
assert.throws(()=>run('preparationReviewPayload()'),/explicitly include linked rows D1/);count++;
field(1,'selected',true);run('preparationDraft().acknowledge=true');
const payload=run('preparationReviewPayload()');check(payload.items.length===3&&payload.items[2].selected===false&&payload.items[1].kind==='definition','Review retains unchecked contextual rows and original role data');
check(payload.items[0].context_ids[0]==='D1'&&payload.items[0].citations[0].page===1,'Review sends source links and numeric citation pages');
const beforeDirtyPropose=requests.length;await run('proposePreparation()');check(requests.length===beforeDirtyPropose,'Dirty drafts never trigger replacement proposals');
field(0,'quote','', {preparationCitation:'0'});run('preparationDraft().acknowledge=true');assert.throws(()=>run('preparationReviewPayload()'),/exact source quotation/);count++;
field(0,'quote',fixture.items[0].citations[0].quote,{preparationCitation:'0'});run('preparationDraft().acknowledge=true');
responder=async(url)=>{if(url.endsWith('/review')){status=409;return {detail:'Stale review revision'};}status=200;return {...fixture,revision:7};};await run('savePreparationReview()');
check(run('preparationDraft().conflict')&&run('preparationDraft().items[0].selected'),'A stale save preserves user selection and fetches the latest revision');
check(node('preparation-error').textContent.includes('Stale review revision'),'Stale server conflict stays readable');
run("preparationAction('rebase',{dataset:{}});preparationDraft().acknowledge=true");responder=async()=>reviewed;await run('savePreparationReview()');
check(run('preparation.current.status')==='reviewed'&&!run('preparationDraft().dirty'),'Successful review records a clean reviewed revision');
check(!node('preparation-use').disabled&&!node('preparation-download').hidden,'Reviewed packets can be downloaded or explicitly handed off');
const packet={requirements:[{id:'R1',text:fixture.items[0].text,source:{document:'spec.pdf',context:{shared:[{id:'D1',role:'definition',quote:'V means volts.'}]}}}]};
for(const id of ['input-tlr','input-sysml','input-context','input-scenarios','input-revision-rationale'])node(id).value='stale';
node('input-name').value='Prepared source';node('input-condition').value='C';node('input-model').value='keep-generator';node('input-feedback').value='2';run('state.uploaded={raw:"stale upload",display:"stale"};state.parent="old-parent"');
responder=async()=>packet;await run('usePreparationPacket()');
check(node('input-format').value==='json'&&node('input-text').value===JSON.stringify(packet),'Handoff uses the complete reviewed JSON packet without flattening source context');
check(run('state.uploaded')===null&&run('state.parent')===null,'Handoff clears uploaded source cache and old revision parent');
check(['input-tlr','input-sysml','input-context','input-scenarios','input-revision-rationale'].every(id=>node(id).value===''),'Handoff removes stale supplied candidate, formal background, development scenarios and revision rationale');
check(node('input-model').value==='keep-generator'&&node('input-feedback').value==='2'&&node('input-condition').value==='C','Selected conversion method, model and repair budget survive handoff');
const runPayload=run('buildRunPayload()');check(runPayload.context===null&&runPayload.development_scenarios===null&&runPayload.tlr===null,'Prepared conversion has no unintended formal premises or supplied candidate');
check(!('assertions' in runPayload)&&requests.every(r=>!r.url.includes('/runs')),'Preparation and handoff never start conversion or assessment and need no assertion suite');
check(node('filename').textContent.includes('Conversion has not started'),'Handoff communicates the remaining explicit conversion action');
const handoffText=node('input-text').value;let releasePacket;responder=()=>new Promise(resolve=>{releasePacket=resolve;});const pendingPacket=run('usePreparationPacket()');field(0,'text','Edited while download was pending');releasePacket(packet);await pendingPacket;
check(node('input-text').value===handoffText&&node('preparation-error').textContent.includes('review changed'),'An edit made while packet loading blocks stale handoff');
run(`preparation.drafts.clear();acceptPreparation(${JSON.stringify(reviewed)});renderPreparation();`);
check(node('preparation-propose').textContent==='Propose again · one new LLM call'&&!node('preparation-propose').disabled,'Reviewed documents can explicitly request a fresh proposal');
responder=async()=>({...fixture,status:'queued',revision:4});await run('proposePreparation()');
check(requests.at(-1).url.endsWith('/propose')&&run('preparationDraft().items.every(row=>!row.selected)'),'Re-proposal never inherits the previous approval selections');
const failedAttempt={number:1,status:'failed',created_at:'2026-10-06T12:00:00Z',started_at:'2026-10-06T12:00:00Z',completed_at:'2026-10-06T12:03:00Z',error:'Earlier timeout <script>bad</script>'};
const failed={...fixture,status:'failed',revision:5,items:[],errors:['Current proposal timed out'],attempts:[failedAttempt],configuration:{proposal_timeout_seconds:180}};
const beforeRetry=requests.length;run(`preparation.drafts.clear();preparation.config={proposal_timeout_seconds:900};acceptPreparation(${JSON.stringify(failed)});renderPreparation();`);
check(node('preparation-propose').textContent==='Retry proposal · one new LLM call'&&!node('preparation-propose').disabled,'Failed proposals offer an explicit one-call retry');
check(node('preparation-body').innerHTML.includes('PDF extraction is retained. No re-upload is needed.'),'Retry retains local PDF extraction and does not require re-upload');
check(requests.length===beforeRetry,'Displaying or resuming a failed preparation never retries automatically');
check(!node('preparation-body').innerHTML.includes('Earlier failed proposal attempts'),'The latest failure is not duplicated as a historical failure');
const queued={...failed,status:'queued',revision:6,errors:[],configuration:{proposal_timeout_seconds:900},attempts:[failedAttempt,{number:2,status:'queued',created_at:'2026-10-06T12:10:00Z'}]};
responder=async()=>queued;await run('proposePreparation()');
check(requests.length===beforeRetry+1&&requests.at(-1).url.endsWith('/propose'),'An explicit retry starts exactly one new proposal request');
check(node('preparation-propose').disabled,'Another proposal cannot be launched while a retry is queued');
context.queuedPreparation=queued;
const queuedTiming=run("preparationTiming(queuedPreparation,Date.parse('2026-10-06T12:10:30Z'))");
check(queuedTiming.includes('Queued for 30s')&&queuedTiming.includes('900 seconds (15 minutes)')&&queuedTiming.includes('once the model call starts'),'Queued elapsed time and model-call timeout are distinct');
const running={...queued,status:'running',attempts:[failedAttempt,{...queued.attempts[1],status:'running',started_at:'2026-10-06T12:11:00Z'}]};context.runningPreparation=running;
check(run("preparationTiming(runningPreparation,Date.parse('2026-10-06T12:13:05Z'))").includes('Running for 2m 5s'),'Running elapsed time uses the actual attempt start rather than queue time');
check(run('preparationTimeout({...runningPreparation,configuration:{proposal_timeout_seconds:1200}})')===1200,'Per-attempt configured timeout takes precedence over a changed service default');
check(run('preparationTimeout({...runningPreparation,configuration:{}})')===900,'Older preparation records use the reported service timeout when not recorded');
check(!run("preparationTiming({...runningPreparation,attempts:[]},Date.now())").includes('NaN'),'Missing timestamps do not invent elapsed progress');
check(run("preparationTiming({...runningPreparation,status:'ready'},Date.now())")==='','Finished proposals no longer display running elapsed time');
run(`acceptPreparation(${JSON.stringify(running)});renderPreparation();`);
check(node('preparation-status').innerHTML.includes('900 seconds (15 minutes)'),'Live preparation status displays the effective proposal time limit');
document.activeElement={insidePreparation:true,tagName:'TEXTAREA'};node('preparation-body').innerHTML='Preserved editor';responder=async()=>running;await run('pollPreparation()');
check(node('preparation-body').innerHTML==='Preserved editor'&&node('preparation-status').innerHTML.includes('Running'),'Polling updates timing without replacing a focused review editor');document.activeElement=null;
const recovered={...fixture,status:'ready',revision:7,errors:[],attempts:[failedAttempt,{...running.attempts[1],status:'ready',completed_at:'2026-10-06T12:14:00Z'}]};run(`acceptPreparation(${JSON.stringify(recovered)});renderPreparation();`);
const recoveredBody=node('preparation-body').innerHTML,historyOffset=recoveredBody.indexOf('<details class="details"><summary>Earlier failed proposal attempts (1)</summary>');
check(historyOffset>=0&&recoveredBody.indexOf('Earlier timeout')>historyOffset&&!recoveredBody.slice(0,historyOffset).includes('Earlier timeout'),'Successful retry places previous failure details in collapsed history');
check(recoveredBody.includes('&lt;script&gt;bad&lt;/script&gt;')&&!recoveredBody.includes('<script>bad'),'Historical failure text is escaped');
check(node('preparation-propose').textContent==='Propose again · one new LLM call'&&!node('preparation-status').innerHTML.includes('failed'),'Successful retry is labeled ready rather than failed');
check(run('preparationDraft().items.every(row=>!row.selected)'),'Successful retry still requires explicit review of all proposed rows');
const settingsRecord={...fixture,configuration:{model:'latest-model',reasoning_effort:'high'},attempts:[{number:1,status:'failed'},{number:2,status:'ready',model:'<script>saved-model</script>',reasoning_effort:'medium'}]};
run(`acceptPreparation(${JSON.stringify(settingsRecord)});renderPreparation();`);
check(node('preparation-status').innerHTML.includes('&lt;script&gt;saved-model&lt;/script&gt;')&&!node('preparation-status').innerHTML.includes('<script>'),'Recorded model names are escaped in live status');
const settingsHistory=node('preparation-body').innerHTML;
check(settingsHistory.includes('Proposal settings by attempt (2)')&&settingsHistory.includes('Reasoning effort: medium'),'Attempt history preserves each recorded configuration');
check(settingsHistory.includes('Model: not recorded · Reasoning effort: not recorded'),'Legacy attempt settings are identified as unrecorded rather than inferred from current defaults');
check(!settingsHistory.includes('<script>saved-model'),'Recorded attempt settings are escaped in history');
check(run("preparationAttemptSettings({...preparation.current,attempts:[],configuration:{model:'legacy-model'}})").includes('Model: legacy-model · Reasoning effort: not recorded'),'Legacy saved model remains visible even if its effort was not recorded');
// Bulk selection includes context dependencies without accepting or submitting a review.
run(`preparation.drafts.clear();preparation.busy=false;acceptPreparation(${JSON.stringify(fixture)});renderPreparation();`);
const bulkStart=requests.length;
check(node('preparation-body').innerHTML.includes('data-preparation-action="select-all"')&&node('preparation-body').innerHTML.includes('data-preparation-action="clear-selection"'),'Visible Select all and Clear selection controls use the existing preparation action handler');
check(!node('preparation-select-all').disabled&&node('preparation-clear-selection').disabled,'An unchecked proposal offers Select all and disables the empty clear action');
check(node('preparation-selection-count').textContent==='0 of 1 requirements and 0 of 2 context items selected','The count distinguishes requirements from contextual items');
field(0,'text','Edited source wording');field(0,'note','Reviewed wording correction');
run('preparationDraft().reviewer="Engineer";preparationDraft().note="Reviewed scope";preparationDraft().expanded.R1=true;preparationDraft().acknowledge=true;');
node('preparation-acknowledge').checked=true;
const preservedRows=run('JSON.stringify(preparationDraft().items.map(({selected,...row})=>row))'),beforeBulkVersion=run('preparationDraft().version');
const selectAllButton={id:'preparation-select-all',disabled:false,dataset:{preparationAction:'select-all'}};
await Promise.all(events.click.map(listener=>listener({target:{closest:()=>selectAllButton}})));
check(run('preparationDraft().items.every(row=>row.selected)'),'Select all includes every requirement, definition and exception, including rows with existing issues');
check(run('preparationDraft().items[0].context_ids[0]')==='D1'&&run('preparationDraft().items[1].selected'),'Bulk selection includes the linked definition alongside its requirement');
check(run('JSON.stringify(preparationDraft().items.map(({selected,...row})=>row))')===preservedRows,'Bulk selection preserves edited text, citations, links, notes, classifications and issues');
check(run('preparationDraft().reviewer')==='Engineer'&&run('preparationDraft().note')==='Reviewed scope'&&run('preparationDraft().expanded.R1'),'Reviewer fields and expanded detail state survive selection');
check(run('preparationDraft().dirty')&&!run('preparationDraft().acknowledge')&&!node('preparation-acknowledge').checked&&run('preparationDraft().version')===beforeBulkVersion+1,'One bulk selection marks the draft dirty and requires renewed acknowledgment');
check(node('preparation-select-all').disabled&&!node('preparation-clear-selection').disabled&&node('preparation-selection-count').textContent==='1 of 1 requirements and 2 of 2 context items selected','Controls and count reflect all selected rows');
check(requests.length===bulkStart&&run('preparation.current.status')==='ready','Selecting all does not save, approve, propose, convert or call an API');
assert.throws(()=>run('preparationReviewPayload()'),/Acknowledge/);count++;
run('preparationDraft().acknowledge=true;preparationDraft().reviewer="";');
assert.throws(()=>run('preparationReviewPayload()'),/reviewer name/);count++;
run('preparationDraft().reviewer="Engineer";');
const afterBulkVersion=run('preparationDraft().version');run("preparationAction('select-all',{dataset:{}})");
check(run('preparationDraft().version')===afterBulkVersion&&run('preparationDraft().acknowledge'),'Repeating an unchanged bulk selection does not invalidate an existing acknowledgment');
field(1,'selected',false);
check(node('preparation-selection-count').textContent==='1 of 1 requirements and 1 of 2 context items selected'&&!node('preparation-select-all').disabled,'Individual checkbox edits refresh the selection count and bulk actions');
run('preparationDraft().acknowledge=true;');assert.throws(()=>run('preparationReviewPayload()'),/linked rows D1/);count++;
run("preparationAction('select-all',{dataset:{}});preparationDraft().acknowledge=true;");
check(run('preparationReviewPayload().items.filter(row=>row.selected).length')===3,'Bulk selection satisfies existing context-link validation without dropping siblings');
field(2,'quote','',{preparationCitation:'0'});run('preparationDraft().acknowledge=true;');
assert.throws(()=>run('preparationReviewPayload()'),/E1:.*exact source quotation/);count++;
check(run('preparationDraft().items[2].selected')&&run('preparationDraft().items[2].issues.length')===1,'Bulk-selected problematic items remain visible and subject to normal validation');
run("preparationAction('clear-selection',{dataset:{}})");
check(run('preparationDraft().items.every(row=>!row.selected)')&&!run('preparationDraft().acknowledge'),'Clear selection removes both requirements and context and resets acknowledgment');
check(node('preparation-clear-selection').disabled&&!node('preparation-select-all').disabled&&node('preparation-selection-count').textContent==='0 of 1 requirements and 0 of 2 context items selected','Clear selection refreshes controls and counts');
check(run('preparationDraft().items[0].text')==='Edited source wording'&&run('preparationDraft().items[0].context_ids[0]')==='D1','Clearing selection preserves draft edits and suggested context relationships');
for(const status of ['queued','pending','running']){
  run(`preparation.current.status='${status}';updatePreparationStatus();`);
  check(node('preparation-select-all').disabled&&node('preparation-clear-selection').disabled,`Both bulk controls are disabled while ${status}`);
  run("preparationAction('select-all',{dataset:{}})");
  check(run('preparationDraft().items.every(row=>!row.selected)'),`Programmatic bulk changes are also rejected while ${status}`);
}
run("preparation.current.status='ready';preparation.busy=true;updatePreparationStatus();preparationAction('select-all',{dataset:{}})");
check(node('preparation-select-all').disabled&&node('preparation-clear-selection').disabled&&run('preparationDraft().items.every(row=>!row.selected)'),'An in-flight API operation disables and blocks bulk selection');
check(requests.length===bulkStart,'All bulk and individual selection checks remain local without requests');
run(`preparation.busy=false;preparation.drafts.clear();acceptPreparation(${JSON.stringify({...fixture,items:[]})});renderPreparation();`);
check(node('preparation-select-all').disabled&&node('preparation-clear-selection').disabled,'No proposal rows disables both bulk controls');
run("preparationAction('select-all',{dataset:{}});preparationAction('clear-selection',{dataset:{}})");
check(!run('preparationDraft().dirty'),'Empty bulk actions leave the draft unchanged');
console.log(`${count} PDF preparation workbench checks passed`);
})().catch(error=>{console.error(error);process.exitCode=1;});
